"""
Report generation service for Sentinel Risk.
Generates PDF reports from analysis results.
"""

import os
from datetime import datetime


def create_report(
    analysis_id: str,
    company_name: str,
    period: str,
    ratios: list[dict],
    template: str = "professional",
    language: str = "en",
    include_charts: bool = True,
) -> str:
    """
    Generate a PDF report for the analysis.
    
    Returns the file path of the generated report.
    """
    output_dir = os.path.join(os.path.expanduser("~"), ".sentinel-risk", "reports")
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, f"report_{analysis_id[:8]}.pdf")
    
    # Phase 2: Implement full ReportLab-based PDF generation
    # For now, create a placeholder
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas
    from reportlab.lib.units import mm
    
    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4
    
    # Header bar
    c.setFillColorRGB(0.29, 0.28, 0.20)  # #4e4732
    c.rect(0, height - 40*mm, width, 40*mm, fill=True, stroke=False)
    
    # Title
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(20*mm, height - 20*mm, "Sentinel Risk")
    
    c.setFillColorRGB(0.57, 0.46, 0.12)  # #92761f
    c.setFont("Helvetica", 12)
    c.drawString(20*mm, height - 28*mm, "Financial Analysis Report")
    
    # Company info
    c.setFillColorRGB(0.26, 0.26, 0.25)  # #1a1a19
    c.setFont("Helvetica-Bold", 18)
    c.drawString(20*mm, height - 55*mm, company_name)
    
    c.setFillColorRGB(0.47, 0.44, 0.42)  # #78716c
    c.setFont("Helvetica", 12)
    c.drawString(20*mm, height - 62*mm, f"Period: {period}")
    c.drawString(20*mm, height - 68*mm, f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    
    # Ratio tables
    y = height - 85*mm
    
    categories = {}
    for r in ratios:
        cat = r["category"].title()
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(r)
    
    status_colors = {
        "good": (0.09, 0.64, 0.29),
        "warning": (0.85, 0.47, 0.02),
        "critical": (0.86, 0.15, 0.15),
    }
    
    for cat_name, cat_ratios in categories.items():
        if y < 50*mm:
            c.showPage()
            y = height - 30*mm
        
        # Category header
        c.setFillColorRGB(0.29, 0.28, 0.20)
        c.rect(20*mm, y + 2*mm, width - 40*mm, 8*mm, fill=True, stroke=False)
        c.setFillColorRGB(1, 1, 1)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(22*mm, y + 4*mm, cat_name)
        y -= 12*mm
        
        for r in cat_ratios:
            if y < 40*mm:
                c.showPage()
                y = height - 30*mm
            
            # Ratio name
            c.setFillColorRGB(0.26, 0.26, 0.25)
            c.setFont("Helvetica", 10)
            name = r["ratio_name"].replace("_", " ").title()
            c.drawString(22*mm, y, name)
            
            # Value
            display_val = f"{r['value']*100:.1f}%" if r["unit"] == "%" else f"{r['value']:.2f} {r['unit']}"
            c.setFont("Helvetica-Bold", 10)
            c.drawString(90*mm, y, display_val)
            
            # Status indicator
            sc = status_colors.get(r["status"], (0.47, 0.44, 0.42))
            c.setFillColorRGB(*sc)
            c.circle(140*mm, y + 1.5*mm, 2*mm, fill=True, stroke=False)
            c.setFillColorRGB(0.47, 0.44, 0.42)
            c.setFont("Helvetica", 9)
            c.drawString(144*mm, y, r["status"].title())
            
            y -= 7*mm
        
        y -= 5*mm
    
    # Footer
    c.setFillColorRGB(0.47, 0.44, 0.42)
    c.setFont("Helvetica", 8)
    c.drawString(20*mm, 15*mm, "Generated by Sentinel Risk - Professional Financial Statement Analysis")
    c.drawRightString(width - 20*mm, 15*mm, f"Analysis ID: {analysis_id[:8]}")
    
    c.save()
    return file_path
